package com.peakconnect.job

import com.peakconnect.repository.SlotRepository
import com.peakconnect.risk.WeatherClient
import com.peakconnect.risk.RiskCalculator
import org.springframework.cache.CacheManager
import org.springframework.scheduling.annotation.Scheduled
import org.springframework.stereotype.Component
import org.springframework.transaction.annotation.Transactional
import java.time.LocalDateTime
import org.slf4j.LoggerFactory

@Component
class WeatherRefreshJob(
    private val slotRepository: SlotRepository,
    private val weatherClient: WeatherClient,
    private val riskCalculator: RiskCalculator,
    private val cacheManager: CacheManager
) {
    private val logger = LoggerFactory.getLogger(WeatherRefreshJob::class.java)

    @Scheduled(fixedRateString = "\${scheduler.weather-refresh-interval-ms:1800000}")
    @Transactional(readOnly = true)
    fun refreshWeatherRisk() {
        val upcomingSlots = slotRepository.findByDateAfter(LocalDateTime.now())
        if (upcomingSlots.isEmpty()) return

        var apiCalls = 0
        var slotsRefreshed = 0

        // Group by location to minimize API calls
        val slotsByLocation = upcomingSlots.groupBy { it.activity.location }
        
        val riskCache = cacheManager.getCache("riskCache")

        for ((location, slots) in slotsByLocation) {
            val weather = weatherClient.getWeather(location)
            apiCalls++
            val risk = riskCalculator.calculateRisk(weather)
            
            for (slot in slots) {
                // Key format matches what is generated by @Cacheable in RiskCalculator
                val cacheKey = "${slot.id}-$location"
                riskCache?.put(cacheKey, risk)
                slotsRefreshed++
            }
        }
        
        logger.info("WeatherRefreshJob completed: made $apiCalls API calls, refreshed risk for $slotsRefreshed slots.")
    }
}
