spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
